# Generated by Django 5.0.7 on 2024-07-23 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название оборудования')),
                ('description', models.TextField(max_length=350, verbose_name='Описание')),
                ('is_free', models.CharField(choices=[('Ready_to_use', 'Ready'), ('Used_in_another_contract', 'Busy'), ('Need_to_be_repair', 'Broken')], verbose_name='Свободно для использования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название услуги')),
                ('description', models.TextField(max_length=350)),
                ('illustration', models.ImageField(blank=True, upload_to='')),
                ('equipment_used', models.ManyToManyField(blank=True, to='services.equipment')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(blank=True, unique=True)),
                ('signed_date', models.DateField(verbose_name='Дата подписания')),
                ('completed', models.BooleanField(verbose_name='Закончен?')),
                ('completed_date', models.DateField(verbose_name='Дата завершения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.client')),
                ('equipment_required', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.equipment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
