# Generated by Django 5.0.7 on 2024-07-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_building',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер здания'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк получателя'),
        ),
        migrations.AddField(
            model_name='client',
            name='bik',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='client',
            name='checking_account',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='client',
            name='correspondent_account',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='kpp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='client',
            name='post_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=12, verbose_name='Контактный номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='organization_name',
            field=models.CharField(max_length=150, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='equipment_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.equipment', verbose_name='Необходимое оборудование'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, unique=True, verbose_name='Номер контракта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=350, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='equipment_used',
            field=models.ManyToManyField(blank=True, to='services.equipment', verbose_name='Используемое оборудование'),
        ),
        migrations.AlterField(
            model_name='service',
            name='illustration',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация'),
        ),
    ]
