# Generated by Django 5.0.7 on 2024-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_client_address_building_client_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
