# Generated by Django 5.0.7 on 2024-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_contract_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
